service: react

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: sysadmin
  region: us-east-1
  memorySize: 128
  timeout: 20

package:
 include:
   - node_modules/**

functions:
  create:
    name: ${self:service}-${self:provider.stage}-create
    handler: create.action
    description: The most basic aws lambda
    events:
      - http:
          path: ${self:service}/create
          method: get
          cors: true

  read:
    name: ${self:service}-${self:provider.stage}-read
    handler: read.action
    description: The most basic aws lambda
    events:
      - http:
          path: ${self:service}/read
          method: get
          cors: true

  update:
    name: ${self:service}-${self:provider.stage}-update
    handler: update.action
    description: The most basic aws lambda
    events:
      - http:
          path: ${self:service}/update
          method: get
          cors: true

  remove:
    name: ${self:service}-${self:provider.stage}-remove
    handler: remove.action
    description: The most basic aws lambda
    events:
      - http:
          path: ${self:service}/remove
          method: get
          cors: true

