service: react

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: sysadmin
  region: us-east-1
  memorySize: 128
  timeout: 30 # Change this to a sensible value later
  vpc:
    securityGroupIds:
      - sg-daaf4ba6
    subnetIds:
      - subnet-b41ba888
      - subnet-e372c0ef
      - subnet-87a0c6dc
      - subnet-c06009ed
      - subnet-cf217f86
      - subnet-751f9110

package:
 include:
   - ./node_modules/**
   - ./lib/**

functions:
  create:
    name: ${self:service}-${self:provider.stage}-create
    handler: create.action
    description: Create Todo
    events:
      - http:
          path: ${self:service}/create
          method: post
          cors: true

  read:
    name: ${self:service}-${self:provider.stage}-read
    handler: read.action
    description: Read Todos
    events:
      - http:
          path: ${self:service}/read
          method: get
          cors: true

  update:
    name: ${self:service}-${self:provider.stage}-update
    handler: update.action
    description: Update Todo
    events:
      - http:
          path: ${self:service}/update
          method: get
          cors: true

  delete:
    name: ${self:service}-${self:provider.stage}-delete
    handler: delete.action
    description: Delete Todo
    events:
      - http:
          path: ${self:service}/delete
          method: get
          cors: true

